routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PublicController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DepartmentController;

use App\Http\Controllers\LogsController;
use App\Http\Controllers\AbsencesController;
use App\Http\Controllers\UnderTimeController;
use App\Http\Controllers\OverTimeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PublicController::class, 'index'])->name('home');
Route::get('/scan/{id}', [PublicController::class, 'scanner'])->name('scanner');

Route::get('/autofill', [PublicController::class, 'autofill'])->name('autofill');

Route::get('/time-in', [PublicController::class, 'timein'])->name('timein');
Route::get('/time-out', [PublicController::class, 'timeout'])->name('timeout');
Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
Route::get('/log', [PublicController::class, 'log'])->name('log');
Route::get('/clear', [PublicController::class, 'clear'])->name('clear');

Route::post('/leave/{id}', [UserController::class, 'leave'])->name('leave');
Route::delete('/leave/{id}/delete', [UserController::class, 'leave_delete'])->name('leave-delete');

require __DIR__.'/auth.php';

Auth::routes([
  'register' => false, // Registration Routes...
]);

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('departments', DepartmentController::class);

    Route::resource('logs', LogsController::class);
    Route::resource('absences', AbsencesController::class);
    Route::resource('undertime', UnderTimeController::class);
    Route::resource('overtime', OverTimeController::class);
});

app/Http/Controllers/AbsencesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Absent;
use App\Models\User;

class AbsencesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:absent-list|absent-create|absent-edit|absent-delete', ['only' => ['index','show']]);
         $this->middleware('permission:absent-create', ['only' => ['create','store']]);
         $this->middleware('permission:absent-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:absent-delete', ['only' => ['destroy']]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $absences = Absent::latest()->paginate(10);
        return view('absences.index',compact('absences'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employees = User::where('role','=','employee')->get();
        return view('absences.create', compact('employees'));
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'date' => 'required',
            'cause' => 'required',
            'reason' => 'required',
            'user_id' => 'required',
        ]);
    
        Absent::create($request->all());
    
        return redirect()->route('absences.index')
                        ->with('success','Absent created successfully.');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\Absent  $absent
     * @return \Illuminate\Http\Response
     */
    public function show(Absent $absent)
    {
        return view('absences.show',compact('absent'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Absent  $absent
     * @return \Illuminate\Http\Response
     */
    public function edit(Absent $absent)
    {
        $employees = User::where('role','=','employee')->get();
        return view('absences.edit',compact('absent','employees'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Absent  $absent
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Absent $absent)
    {
         request()->validate([
            'date' => 'required',
            'cause' => 'required',
            'reason' => 'required',
            'user_id' => 'required',
        ]);
    
        $absent->update($request->all());
    
        return redirect()->route('absences.index')
                        ->with('success','Absent updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Absent  $absent
     * @return \Illuminate\Http\Response
     */
    public function destroy(Absent $absent)
    {
        $absent->delete();
    
        return redirect()->route('absences.index')
                        ->with('success','Absent deleted successfully');
    }
}

resources/views/absences/create.blade.php
@extends('layouts.neon')

@section('title')
<div class="pull-left">
    <h2>Create a Record of Absence</h2>
</div>
@endsection


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            
            <a class="btn btn-default" href="{{ route('absences.index') }}"><i class="entypo-left-bold"></i> Go Back</a>
            
        </div>
    </div>

    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('absences.store') }}" method="POST">
    	@csrf
        <div class="row">
		    <div class="col-xs-12 col-sm-6 col-md-6">
		        <div class="form-group">
		            <strong>Date:</strong>
		            <input type="text" name="date" class="form-control" placeholder="{{ date('m/d/Y') }}">
		        </div>
		    </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Cause:</strong>
                    <select name="cause" class="form-control">
                        <option value="other">Other</option>
                        <option value="sick-leave">Sick Leave</option>
                        <option value="vacation-leave">Vacation Leave</option>
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Reason:</strong>
                    <textarea name="reason" rows="3" class="form-control" placeholder="Other reasons for being absent."></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Employee:</strong>
                    <select name="user_id" class="form-control">
                        @foreach($employees as $employee)
                        <option value="{{ $employee->id }}">{{ $employee->last_name.', '.$employee->first_name.' '.$employee->middle_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
                <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
    </form>

@endsection

resources/views/absences/edit.blade.php
@extends('layouts.neon')


@section('title')
<div class="pull-left">
    <h2>Edit Record</h2>
</div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            
            <a class="btn btn-default" href="{{ route('absences.index') }}"><i class="entypo-left-bold"></i> Go Back</a>
            
        </div>
    </div>
    <hr>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('absences.update',$absent->id) }}" method="POST">
    	@csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Date:</strong>
                    <input type="text" value="{{ $absent->date }}" name="date" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Cause:</strong>
                    <select name="cause" class="form-control">
                        <option value="other" {{ $absent->cause=='other' ? ' selected':'' }}>Other</option>
                        <option value="sick-leave" {{ $absent->cause=='sick-leave' ? ' selected':'' }}>Sick Leave</option>
                        <option value="vacation-leave" {{ $absent->cause=='vacation-leave' ? ' selected':'' }}>Vacation Leave</option>
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Reason:</strong>
                    <textarea name="reason" rows="3" class="form-control" placeholder="Other reasons for being absent.">{{ $absent->reason }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Employee:</strong>
                    <select name="user_id" class="form-control">
                        @foreach($employees as $employee)
                        <option value="{{ $employee->id }}" {{ $absent->user_id == $employee->id ? ' selected':'' }}>{{ $employee->last_name.', '.$employee->first_name.' '.$employee->middle_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>

@endsection

resources/views/absences/index.blade.php
@extends('layouts.neon')

@section('title')
<div class="pull-left">
    <h2>Records of Absences</h2>
</div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="float-right">
                @can('absent-create')
                <a class="btn btn-success" href="{{ route('absences.create') }}"> Create new record</a>
                @endcan
            </div>
        </div>
    </div>

    <hr>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="card">
        <div class="card-body">

            @if( $absences->count() )

                <table class="table table-bordered">
                    <tr>
                        <th>Employee</th>
                        <th>Date</th>
                        <th>Cause</th>
                        <th width="280px">Action</th>
                    </tr>
                    @foreach ($absences as $absent)
                    <tr>
                        <td>{{ $absent->user->last_name.', '.$absent->user->first_name.' '.$absent->user->middle_name }}</td>
                        <td>{{ $absent->date }}</td>
                        <td>{{ ucfirst( str_replace('-', ' ', $absent->cause) ) }}</td>
                        <td>
                            <form action="{{ route('absences.destroy',$absent->id) }}" method="POST">
                                {{-- <a class="btn btn-info btn-xs" href="{{ route('absences.show',$absent->id) }}">Details</a> --}}
                                @can('absent-edit')
                                <a class="btn btn-primary btn-xs" href="{{ route('absences.edit',$absent->id) }}">Edit</a>
                                @endcan
                                @csrf
                                @method('DELETE')
                                @can('absent-delete')
                                <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                                @endcan
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>

                {!! $absences->links() !!}

            @else

                <div class="alert alert-info alert-dismissible show" role="alert">
                  There are no available data to show at the moment.
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

            @endif

        </div>
    </div>

    

@endsection

resources/views/absences/show.blade.php
@extends('layouts.neon')

@section('title')
<div class="pull-left">
    <h2> Show Client</h2>
</div>
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <a class="btn btn-default" href="{{ route('clients.index') }}"><i class="entypo-left-bold"></i> Go Back</a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $client->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $client->email }}
            </div>
        </div>
        
    </div>

@endsection