routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PublicController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DepartmentController;

use App\Http\Controllers\LogsController;
use App\Http\Controllers\AbsencesController;
use App\Http\Controllers\UnderTimeController;
use App\Http\Controllers\OverTimeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PublicController::class, 'index'])->name('home');
Route::get('/scan/{id}', [PublicController::class, 'scanner'])->name('scanner');

Route::get('/autofill', [PublicController::class, 'autofill'])->name('autofill');

Route::get('/time-in', [PublicController::class, 'timein'])->name('timein');
Route::get('/time-out', [PublicController::class, 'timeout'])->name('timeout');
Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
Route::get('/log', [PublicController::class, 'log'])->name('log');
Route::get('/clear', [PublicController::class, 'clear'])->name('clear');

Route::post('/leave/{id}', [UserController::class, 'leave'])->name('leave');
Route::delete('/leave/{id}/delete', [UserController::class, 'leave_delete'])->name('leave-delete');

require __DIR__.'/auth.php';

Auth::routes([
  'register' => false, // Registration Routes...
]);

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('departments', DepartmentController::class);

    Route::resource('logs', LogsController::class);
    Route::resource('absences', AbsencesController::class);
    Route::resource('undertime', UnderTimeController::class);
    Route::resource('overtime', OverTimeController::class);
});

app/Models/OverTime.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OverTime extends Model
{
    use HasFactory;

    //assign primary key field name.
    protected $primaryKey = 'id';
    //database table name.
    protected $table = 'overtimes';

    protected $fillable = [
        'time',
        'user_id',
    ];

    public function user()
    {
        return $this->hasOne('App\Models\User','user_id');
    }
}

app/Http/Controllers/OverTimeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Overtime;
use App\Models\User;

class OverTimeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:overtime-list|overtime-create|overtime-edit|overtime-delete', ['only' => ['index','show']]);
         $this->middleware('permission:overtime-create', ['only' => ['create','store']]);
         $this->middleware('permission:overtime-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:overtime-delete', ['only' => ['destroy']]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $overtime = OverTime::latest()->paginate(10);
        return view('overtime.index',compact('overtime'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return redirect()->route('overtime.index');
        // return view('overtime.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'time' => 'required',
            'user_id' => 'required|integer',
        ]);
    
        OverTime::create($request->all());
    
        return redirect()->route('overtime.index')
                        ->with('success','OverTime created successfully.');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\OverTime  $overtime
     * @return \Illuminate\Http\Response
     */
    public function show(OverTime $overtime)
    {
        return redirect()->route('overtime.index');
        // return view('overtime.show',compact('overtime'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\OverTime  $overtime
     * @return \Illuminate\Http\Response
     */
    public function edit(OverTime $overtime)
    {
        $employees = User::where('role','=','employee')->get();
        return view('overtime.edit',compact('overtime','employees'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\OverTime  $overtime
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, OverTime $overtime)
    {
         request()->validate([
            'time' => 'required',
            'user_id' => 'required|integer',
        ]);
    
        $overtime->update($request->all());
    
        return redirect()->route('overtime.index')
                        ->with('success','OverTime updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\OverTime  $overtime
     * @return \Illuminate\Http\Response
     */
    public function destroy(OverTime $overtime)
    {
        $overtime->delete();
    
        return redirect()->route('overtime.index')
                        ->with('success','OverTime deleted successfully');
    }
}

resources/views/overtime/edit.blade.php
@extends('layouts.neon')


@section('title')
<div class="pull-left">
    <h2>Edit Overtime</h2>
</div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            
            <a class="btn btn-default" href="{{ route('overtime.index') }}"><i class="entypo-left-bold"></i> Go Back</a>
            
        </div>
    </div>
    <hr>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('overtime.update',$overtime->id) }}" method="POST">
    	@csrf
        @method('PUT')


        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Time:</strong>
                    <input type="text" name="name" value="{{ $overtime->time }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Employee:</strong>
                    <select name="user_id" class="form-control">
                        @foreach($employees as $employee)
                        <option value="{{ $employee->id }}" {{ $overtime->user_id == $employee->id ? ' selected':'' }}>{{ $employee->last_name.', '.$employee->first_name.' '.$employee->middle_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

		    <div class="col-xs-12 col-sm-12 col-md-12">
		      <button type="submit" class="btn btn-primary">Save</button>
		    </div>
		</div>


    </form>

@endsection

resources/views/overtime/index.blade.php
@extends('layouts.neon')

@section('title')
<div class="pull-left">
    <h2>Overtime Records</h2>
</div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="float-right">
                @can('overtime-create')
                {{-- <a class="btn btn-success" href="{{ route('overtime.create') }}"> Create New Record</a> --}}
                @endcan
            </div>
        </div>
    </div>

    {{-- <hr> --}}
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="card">
        <div class="card-body">

            @if( $overtime->count() )

                <table class="table table-bordered">
                    <tr>
                        <th>Employee</th>
                        <th>Time</th>
                        <th width="280px">Action</th>
                    </tr>
                    @foreach ($overtime as $record)
                    <tr>
                        <td>{{ $record->user->last_name.', '.$record->user->first_name.' '.$record->user->middle_name }}</td>
                        <td>{{ $record->time }}</td>
                        <td>
                            <form action="{{ route('overtime.destroy',$record->id) }}" method="POST">
                                <a class="btn btn-info btn-xs" href="{{ route('overtime.show',$record->id) }}">Details</a>
                                @can('overtime-edit')
                                <a class="btn btn-primary btn-xs" href="{{ route('overtime.edit',$record->id) }}">Edit</a>
                                @endcan
                                @csrf
                                @method('DELETE')
                                @can('overtime-delete')
                                <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                                @endcan
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>

                {!! $overtime->links() !!}

            @else

                <div class="alert alert-info alert-dismissible show" role="alert">
                  There are no available data to show at the moment.
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

            @endif

        </div>
    </div>

    

@endsection